swagger: '2.0'
info:
  title: Netflix API
  description: API for managing Netflix content.
  version: "1.0.0"
host: localhost:8080
basePath: /
schemes:
  - http

paths:
  /content:
    get:
      summary: Retrieve all content
      description: Obtén una lista de todos los elementos de contenido disponibles en la plataforma.
      tags:
        - Content
      responses:
        '200':
          description: Una lista de todos los elementos de contenido
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: "Contenido de ejemplo"
                    description:
                      type: string
                      example: "Descripción del contenido de ejemplo"
                    release_date:
                      type: string
                      format: date-time
                      example: "2024-05-19T12:00:00Z"
                    type:
                      type: string
                      example: "video"
                    url_content:
                      type: string
                      example: "http://example.com/content/1"
                    url_cover:
                      type: string
                      example: "http://example.com/cover/1"
    post:
      summary: Create a new content item
      description: Crea un nuevo elemento de contenido proporcionando los detalles necesarios en el cuerpo de la solicitud.
      tags:
        - Content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Content'
      responses:
        '201':
          description: Contenido creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/definitions/Content'
              example:
                id: 2
                title: "Nuevo contenido de ejemplo"
                description: "Descripción del nuevo contenido de ejemplo"
                release_date: "2024-06-20T12:00:00Z"
                type: "video"
                url_content: "http://example.com/content/2"
                url_cover: "http://example.com/cover/2"

  /content/{id}:
    get:
      summary: Retrieve content by ID
      description: Obtén los detalles de un elemento de contenido específico usando su ID único.
      tags:
        - Content
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El ID del contenido a recuperar
      responses:
        '200':
          description: Detalles del contenido recuperado
          content:
            application/json:
              schema:
                $ref: '#/definitions/Content'
              example:
                id: 1
                title: "Contenido de ejemplo"
                description: "Descripción del contenido de ejemplo"
                release_date: "2024-05-19T12:00:00Z"
                type: "video"
                url_content: "http://example.com/content/1"
                url_cover: "http://example.com/cover/1"
        '404':
          description: Contenido no encontrado
    put:
      summary: Update a content item
      description: Actualiza los detalles de un elemento de contenido existente usando su ID único.
      tags:
        - Content
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El ID del contenido a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Content'
      responses:
        '200':
          description: Contenido actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/definitions/Content'
              example:
                id: 1
                title: "Contenido actualizado"
                description: "Descripción actualizada del contenido"
                release_date: "2024-05-19T12:00:00Z"
                type: "video"
                url_content: "http://example.com/content/1"
                url_cover: "http://example.com/cover/1"
    delete:
      summary: Delete a content item
      description: Elimina un elemento de contenido existente usando su ID único.
      tags:
        - Content
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El ID del contenido a eliminar
      responses:
        '204':
          description: Contenido eliminado exitosamente

  /users:
    get:
      summary: Retrieve all users
      description: Obtén una lista de todos los usuarios registrados en la plataforma.
      tags:
        - User
      responses:
        '200':
          description: Una lista de todos los usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    username:
                      type: string
                      example: "usuario1"
                    email:
                      type: string
                      example: "usuario1@example.com"
                    created_at:
                      type: string
                      format: date-time
                      example: "2024-05-19T12:00:00Z"
    post:
      summary: Create a new user
      description: Crea un nuevo usuario proporcionando los detalles necesarios en el cuerpo de la solicitud.
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/User'
      responses:
        '201':
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/definitions/User'
              example:
                id: 1
                username: "usuario1"
                email: "usuario1@example.com"
                created_at: "2024-05-19T12:00:00Z"

  /users/{email}:
    get:
      summary: Retrieve user by email
      description: Obtén los detalles de un usuario específico usando su correo electrónico único.
      tags:
        - User
      parameters:
        - in: path
          name: email
          schema:
            type: string
          required: true
          description: El correo electrónico del usuario a recuperar
      responses:
        '200':
          description: Detalles del usuario recuperado
          content:
            application/json:
              schema:
                $ref: '#/definitions/User'
              example:
                id: 1
                username: "usuario1"
                email: "usuario1@example.com"
                created_at: "2024-05-19T12:00:00Z"
        '404':
          description: Usuario no encontrado
    put:
      summary: Update a user
      description: Actualiza los detalles de un usuario existente usando su correo electrónico único.
      tags:
        - User
      parameters:
        - in: path
          name: email
          schema:
            type: string
          required: true
          description: El correo electrónico del usuario a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/User'
      responses:
        '200':
          description: Usuario actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/definitions/User'
              example:
                id: 1
                username: "usuario1"
                email: "usuario1@example.com"
                created_at: "2024-05-19T12:00:00Z"
    delete:
      summary: Delete a user
      description: Elimina un usuario existente usando su correo electrónico único.
      tags:
        - User
      parameters:
        - in: path
          name: email
          schema:
            type: string
          required: true
          description: El correo electrónico del usuario a eliminar
      responses:
        '204':
          description: Usuario eliminado exitosamente

  /subscriptions:
    get:
      summary: Retrieve all subscriptions
      description: Obtén una lista de todas las suscripciones registradas en la plataforma.
      tags:
        - Subscription
      responses:
        '200':
          description: Una lista de todas las suscripciones
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    subscriber_id:
                      type: integer
                      example: 1
                    subscribed_to_id:
                      type: integer
                      example: 2
                    start_date:
                      type: string
                      format: date-time
                      example: "2024-05-19T12:00:00Z"
                    end_date:
                      type: string
                      format: date-time
                      example: "2025-05-19T12:00:00Z"
                    status:
                      type: string
                      example: "active"
    post:
      summary: Create a new subscription
      description: Crea una nueva suscripción proporcionando los detalles necesarios en el cuerpo de la solicitud.
      tags:
        - Subscription
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Subscription'
      responses:
        '201':
          description: Suscripción creada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/definitions/Subscription'
              example:
                id: 1
                subscriber_id: 1
                subscribed_to_id: 2
                start_date: "2024-05-19T12:00:00Z"
                end_date: "2025-05-19T12:00:00Z"
                status: "active"

  /subscriptions/{id}:
    get:
      summary: Retrieve subscription by ID
      description: Obtén los detalles de una suscripción específica usando su ID único.
      tags:
        - Subscription
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El ID de la suscripción a recuperar
      responses:
        '200':
          description: Detalles de la suscripción recuperada
          content:
            application/json:
              schema:
                $ref: '#/definitions/Subscription'
              example:
                id: 1
                subscriber_id: 1
                subscribed_to_id: 2
                start_date: "2024-05-19T12:00:00Z"
                end_date: "2025-05-19T12:00:00Z"
                status: "active"
        '404':
          description: Suscripción no encontrada
    put:
      summary: Update a subscription
      description: Actualiza los detalles de una suscripción existente usando su ID único.
      tags:
        - Subscription
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El ID de la suscripción a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Subscription'
      responses:
        '200':
          description: Suscripción actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/definitions/Subscription'
              example:
                id: 1
                subscriber_id: 1
                subscribed_to_id: 2
                start_date: "2024-05-19T12:00:00Z"
                end_date: "2025-05-19T12:00:00Z"
                status: "active"
    delete:
      summary: Delete a subscription
      description: Elimina una suscripción existente usando su ID único.
      tags:
        - Subscription
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El ID de la suscripción a eliminar
      responses:
        '204':
          description: Suscripción eliminada exitosamente

  /interactions:
    get:
      summary: Retrieve all interactions
      description: Obtén una lista de todas las interacciones registradas en la plataforma.
      tags:
        - Interaction
      responses:
        '200':
          description: Una lista de todas las interacciones
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    user_id:
                      type: integer
                      example: 1
                    content_id:
                      type: integer
                      example: 1
                    type:
                      type: string
                      example: "view"
                    timestamp:
                      type: string
                      format: date-time
                      example: "2024-05-19T12:00:00Z"
    post:
      summary: Log a new interaction
      description: Registra una nueva interacción proporcionando los detalles necesarios en el cuerpo de la solicitud.
      tags:
        - Interaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Interaction'
      responses:
        '201':
          description: Interacción registrada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/definitions/Interaction'
              example:
                id: 1
                user_id: 1
                content_id: 1
                type: "view"
                timestamp: "2024-05-19T12:00:00Z"

  /interactions/{id}:
    get:
      summary: Retrieve interaction by ID
      description: Obtén los detalles de una interacción específica usando su ID único.
      tags:
        - Interaction
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El ID de la interacción a recuperar
      responses:
        '200':
          description: Detalles de la interacción recuperada
          content:
            application/json:
              schema:
                $ref: '#/definitions/Interaction'
              example:
                id: 1
                user_id: 1
                content_id: 1
                type: "view"
                timestamp: "2024-05-19T12:00:00Z"
        '404':
          description: Interacción no encontrada
    delete:
      summary: Delete an interaction
      description: Elimina una interacción existente usando su ID único.
      tags:
        - Interaction
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El ID de la interacción a eliminar
      responses:
        '204':
          description: Interacción eliminada exitosamente

  /profiles:
    get:
      summary: Retrieve all profiles
      description: Obtén una lista de todos los perfiles registrados en la plataforma.
      tags:
        - Profile
      responses:
        '200':
          description: Una lista de todos los perfiles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    user_id:
                      type: integer
                      example: 1
                    biography:
                      type: string
                      example: "Biografía de ejemplo"
                    interests:
                      type: array
                      items:
                        type: string
                      example: ["películas", "música"]
                    experience:
                      type: string
                      example: "Experiencia de ejemplo"
                    education:
                      type: string
                      example: "Educación de ejemplo"
    post:
      summary: Create a new profile
      description: Crea un nuevo perfil proporcionando los detalles necesarios en el cuerpo de la solicitud.
      tags:
        - Profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Profile'
      responses:
        '201':
          description: Perfil creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/definitions/Profile'
              example:
                id: 1
                user_id: 1
                biography: "Biografía de ejemplo"
                interests: ["películas", "música"]
                experience: "Experiencia de ejemplo"
                education: "Educación de ejemplo"

  /profiles/{id}:
    get:
      summary: Retrieve profile by ID
      description: Obtén los detalles de un perfil específico usando su ID único.
      tags:
        - Profile
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El ID del perfil a recuperar
      responses:
        '200':
          description: Detalles del perfil recuperado
          content:
            application/json:
              schema:
                $ref: '#/definitions/Profile'
              example:
                id: 1
                user_id: 1
                biography: "Biografía de ejemplo"
                interests: ["películas", "música"]
                experience: "Experiencia de ejemplo"
                education: "Educación de ejemplo"
        '404':
          description: Perfil no encontrado
    put:
      summary: Update a profile
      description: Actualiza los detalles de un perfil existente usando su ID único.
      tags:
        - Profile
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El ID del perfil a actualizar
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Profile'
      responses:
        '200':
          description: Perfil actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/definitions/Profile'
              example:
                id: 1
                user_id: 1
                biography: "Biografía de ejemplo"
                interests: ["películas", "música"]
                experience: "Experiencia de ejemplo"
                education: "Educación de ejemplo"
    delete:
      summary: Delete a profile
      description: Elimina un perfil existente usando su ID único.
      tags:
        - Profile
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: El ID del perfil a eliminar
      responses:
        '204':
          description: Perfil eliminado exitosamente

definitions:
  Content:
    type: object
    required:
      - title
      - description
      - release_date
      - type
      - url_content
      - url_cover
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      description:
        type: string
      release_date:
        type: string
        format: date-time
      type:
        type: string
      url_content:
        type: string
